version: '3'

services: 
  frontend:
    build: .
    image: twiiter-like-sns-frontend
    ports: 
      - "4000:4000"
    container_name: frontend
  backend:
    build: ./test_server
    image: twiiter-like-sns-backend-test
    ports: 
      - "3000:3000"
    container_name: backend_test_server
