version: '3'

services: 
  frontend:
    build: .
    image: twiiter-like-sns-frontend
    ports: 
      - "4000:4000"
    container_name: frontend
  mock:
    build: ./mock
    image: twiiter-like-sns-mock
    ports: 
      - "127.0.0.1:3000:3000"
    container_name: mock