version: '3'

services:
    golang:
        build: ./backend
        ports:
            - "80:8080"
        depends_on:
            - mysql
    # mysql のサービスを追加
    mysql:
      image: mysql:latest
      restart: always #コンテナ起動時に自動起動する設定。自動起動させたくない場合はこの記述を削除すれば良い
      container_name: myapp-db #コンテナの名前を決める、あってもなくても良い
      ports:
        - 5000:3306 #どのポートを開放するかを設定":"の左側はホストのポート、右側はコンテナのポート
      volumes: # ./mysqlと言うローカルディレクトりをコンテナの指定ディレクトリにマウント
        - ./database/init:/docker-entrypoint-initdb.d  
      hostname: mysql
      environment:
        MYSQL_ROOT_USERNAME: ${MYSQL_ROOT_USERNAME}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}